<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Lotta.Tests</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <!-- Using ProjectReferences for local development; switch to PackageReferences for release -->
    <!-- <PackageReference Include="Iciclecreek.Azure.Storage.FileSystem" Version="2.0.1" /> -->
    <!-- <PackageReference Include="Iciclecreek.Azure.Storage.Memory" Version="2.0.0" /> -->
    <!-- <PackageReference Include="Iciclecreek.Azure.Storage.SQLite" Version="2.0.0" /> -->
    <PackageReference Include="Lucene.Net.Store.Azure" Version="4.8.5-beta020" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageReference Include="ElBruno.LocalEmbeddings" Version="1.4.6" />

    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LottaDB\LottaDB.csproj" />
    <ProjectReference Include="..\..\..\Azure.Storage\src\Libraries\Iciclecreek.Azure.Storage.Memory\Iciclecreek.Azure.Storage.Memory.csproj" />
    <ProjectReference Include="..\..\..\Azure.Storage\src\Libraries\Iciclecreek.Azure.Storage.FileSystem\Iciclecreek.Azure.Storage.FileSystem.csproj" />
    <ProjectReference Include="..\..\..\Azure.Storage\src\Libraries\Iciclecreek.Azure.Storage.SQLite\Iciclecreek.Azure.Storage.SQLite.csproj" />
  </ItemGroup>


  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Microsoft.Extensions.DependencyInjection" />
    <Using Include="System.Linq" />
  </ItemGroup>
</Project>
